name: Production workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./TripDayFrontend
    steps:
      - name: Production Code
        uses: actions/checkout@v2

      - name: Use Node.js 22.x
        uses: actions/setup-node@v1
        with:
          node-version: 22.x
      - run: npm install
      - run: npm run lint
      - run: npm run test
      
      - name: Set up SSL certificates
        run: | 
          mkdir -p ssl 
          echo "${{ secrets.SSL_CERT }}" > ssl/cert.pem 
          echo "${{ secrets.SSL_PRIVATE_KEY }}" > ssl/key.pem
      - run: npm run build --if-present
      # - name: Deploy prod to Heroku
      #   uses: akhileshns/heroku-deploy@v3.12.12
      #   with:
      #     args: deploy --dir=build --prod
      #     # args: deploy --dir=build --prod
      #     heroku_api_key: ${{ secrets.HEROKU_TRIP_DAY_API_KEY }}
      #     heroku_app_name: 'trip-day-prod'
      #     heroku_email: 'nientaiho@gmail.com'